from node:16-bullseye

run mkdir -p /indexer/build

copy src/ /indexer/src 
copy package.json /indexer
copy tsconfig.json /indexer
copy config.json /indexer

workdir /indexer

copy eosrio-hyperion-sequential-reader-1.1.0.tgz ./

run yarn install
run npx tsc

env LOG_LEVEL debug

cmd ["node", "--inspect=9229", "--max-old-space-size=8192", "build/main.js"]
